export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';

export const GET_ORDERS_FROM_TELEPHONE = "GET_ORDERS_FROM_TELEPHONE";

export const ORDER_POST_FAIL = "ORDER_POST_FAIL";

export const ORDER_POST_SUCCESS = "ORDER_POST_SUCCESS";

export const GET_ORDER_FAIL = "GET_ORDER_FAIL";